sudo: required

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
    - INSTANCE="kitchen verify" OPTIONS="default-centos-6"
    - INSTANCE="kitchen verify" OPTIONS="default-centos-7"
    - INSTANCE="kitchen verify" OPTIONS="default-debian-8"
    - INSTANCE="kitchen verify" OPTIONS="default-fedora-latest"
    - INSTANCE="kitchen verify" OPTIONS="default-ubuntu-1604"
    - INSTANCE="kitchen verify" OPTIONS="redis-package-centos-6"
    - INSTANCE="kitchen verify" OPTIONS="redis-package-centos-7"
    - INSTANCE="kitchen verify" OPTIONS="redis-package-debian-8"
    - INSTANCE="kitchen verify" OPTIONS="redis-package-fedora-latest"
    - INSTANCE="kitchen verify" OPTIONS="redis-package-ubuntu-1604"
    - INSTANCE="kitchen verify" OPTIONS="sentinel-centos-6"
    - INSTANCE="kitchen verify" OPTIONS="sentinel-centos-7"
    - INSTANCE="kitchen verify" OPTIONS="sentinel-debian-8"
    - INSTANCE="kitchen verify" OPTIONS="sentinel-fedora-latest"
    - INSTANCE="kitchen verify" OPTIONS="sentinel-ubuntu-1604"
    - INSTANCE="kitchen verify" OPTIONS="multisentinel-centos-6"
    - INSTANCE="kitchen verify" OPTIONS="multisentinel-centos-7"
    - INSTANCE="kitchen verify" OPTIONS="multisentinel-debian-8"
    - INSTANCE="kitchen verify" OPTIONS="multisentinel-fedora-latest"
    - INSTANCE="kitchen verify" OPTIONS="multisentinel-ubuntu-1604"
before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=kitchen.dokken.yml CHEF_VERSION=${CHEF_VERSION} kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
  allow_failures:
    # https://github.com/brianbianco/redisio/issues/335
    - env: INSTANCE="kitchen verify" OPTIONS="redis-package-centos-6"
